org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.235
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=astralsorcery
mod_name=Astral Sorcery
mod_license=All Rights Reserved
mod_version=2.0.0
mod_group_id=hellfirepvp.astralsorcery
mod_authors=HellFirePvP
mod_description=Magic mod that draws power from stars and their constellations.

# Dependencies
observerlib_version=1.10.3.31
jei_version=19.21.1.312
gander_version=0.2.31
curios_version=9.5.1+1.21.1
jade_modrinth_version=15.10.3+neoforge