modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="https://github.com/HellFirePvP/AstralSorcery/issues"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="astralsorcery.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://minecraft.curseforge.com/projects/astral-sorcery"
logoFile = "logo.png"
credits="HellFirePvP (code & effects), wiiv & LolloNapo (pixelart), PessiMysterio (sounds), Saereth (texts and misc)"
authors="${mod_authors}"
description='''${mod_description}'''
enumExtensions="META-INF/enumextensions.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"